information/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'cc'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('information.views',
    # 个人信息
    url(r'^personal/(\d*)/$', 'information_personal_view'),
    url(r'^personal/(\d*)/edit/action/$', 'information_personal_edit_action'),

    # 工作经历 start
    url(r'^personal/(\d+)/job/list/$', 'job_list_view'),  # 工作一览view
    url(r'^personal/(\d+)/job/edit/(\d+)/$', 'job_edit_view'),  # 工作编辑view
    url(r'^personal/(\d+)/job/edit/action/$', 'job_edit_action'),  # 工作编辑action
    url(r'^personal/(\d+)/job/add/$', 'job_add_view'),  # 工作添加view
    url(r'^personal/(\d+)/job/delete/action/$', 'job_delete_action'),  # 工作删除action
    # 工作经历 end

    # 教育经历 start
    url(r'^personal/(\d+)/education/list/$', 'education_list_view'),  # 教育一览view
    url(r'^personal/(\d+)/education/edit/(\d+)/$', 'education_edit_view'),  # 教育经历编辑view
    url(r'^personal/(\d+)/education/edit/action/$', 'education_edit_action'),  # 教育经历编辑action
    url(r'^personal/(\d+)/education/add/$', 'education_add_view'),  # 教育经历添加view
    url(r'^personal/(\d+)/education/delete/action/$', 'education_delete_action'),  # 教育经历删除action
    # 教育经历 end

    # 家庭信息 start
    url(r'^personal/(\d+)/family/list/$', 'family_list_view'),  # 家庭信息一览view
    url(r'^personal/(\d+)/family/edit/(\d+)/$', 'family_edit_view'),  # 家庭信息编辑view
    url(r'^personal/(\d+)/family/edit/action/$', 'family_edit_action'),  # 家庭信息编辑action
    url(r'^personal/(\d+)/family/add/$', 'family_add_view'),  # 家庭信息添加view
    url(r'^personal/(\d+)/family/delete/action/$', 'family_delete_action'),  # 家庭信息删除action
    # 家庭信息 end

    url(r'^contacts/$', 'information_contacts_view'),

    )

notice/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'cc'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('notice.views',
    # 公告信息

    url(r'^add/$', 'notice_add_view'),
    url(r'^add/action/$', 'notice_add_action'),
    url(r'^delete/action/$', 'notice_delete_action'),
    url(r'^edit/(\d*)/$', 'notice_edit_view'),
    url(r'^edit/action/$', 'notice_edit_action'),
    url(r'^list/$', 'notice_list_view'),
    url(r'^(\d*)/$', 'notice_view_view'),

    )

personnel_management_system/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'personnel_management_system.views.home', name='home'),
    # url(r'^personnel_management_system/', include('personnel_management_system.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # 默认主页
    url(r'^$', "personnel_management_system.views.index_view"),

    # 账户管理模块
    url(r'^account/', include('account.urls')),

    # 基础信息模块
    url(r'^information/', include('information.urls')),

    # 综合管理模块
    url(r'^comprehensive/', include('comprehensive.urls')),

    # 公告模块
    url(r'^notice/', include('notice.urls')),
)

information/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.forms import ModelForm, Form, DateField, CharField
from django import forms
from django.utils.translation import ugettext_lazy as _

from comprehensive.models import Department, CheckIn
from utility.constant import PERSONAL_SEX_MALE, PERSONAL_STATUS_CHOICE, PERSONAL_STATUS_WORK


class Job(models.Model):
    """
    工作经历
    """
    start_date = models.DateField(u"开始日")  # 工作开始日
    end_date = models.DateField(u"结束日")  # 工作结束日
    company = models.CharField(u"公司名称", max_length=255)  # 公司名称
    position = models.CharField(u"职位", max_length=255)  # 职位
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_job"


class Education(models.Model):
    """
    教育经历
    """
    start_date = models.DateField(u"开始日")  # 开始日
    end_date = models.DateField(u"结束日")  # 结束日
    school = models.CharField(u"学校名称", max_length=255)  # 学校名称
    kind = models.CharField(u"种类", max_length=255)  # 种类
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_education"


class Family(models.Model):
    """
    家庭信息
    """
    name = models.CharField(u"名称", max_length=255)  # 名称
    relationship = models.CharField(u"关系", max_length=255)  # 关系
    mobile_phone = models.CharField(u'手机号', null=True, blank=True, max_length=100)  # 手机号
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_family"


class Personal(models.Model):
    """
    个人信息
    """
    sex = models.PositiveIntegerField(u"性别", default=PERSONAL_SEX_MALE)  # 性别
    birthday = models.DateField(u"出生年月", null=True, blank=True,)  # 出生年月
    phone = models.CharField(u'手机号', null=True, blank=True, max_length=100)  # 手机号
    status = models.PositiveSmallIntegerField(u"员工状态", blank=True, choices=PERSONAL_STATUS_CHOICE, default=PERSONAL_STATUS_WORK)  # 员工状态
    department = models.ForeignKey(Department, null=True, blank=True, related_name="belong_to_personal")  # 个人所属部门
    job = models.ManyToManyField(Job, null=True, blank=True, related_name="personal_job",
                                 db_table="hr_manage_information_personal_job_relationships")  # 工作经历
    education = models.ManyToManyField(Education, null=True, blank=True, related_name="personal_education",
                                       db_table="hr_manage_information_personal_education_relationships")  # 教育经历
    family = models.ManyToManyField(Family, null=True, blank=True, related_name="personal_family",
                                    db_table="hr_manage_information_personal_family_relationships")  # 家庭信息
    check_in = models.ManyToManyField(CheckIn, null=True, blank=True, related_name="personal_check_in",
                                      db_table="hr_manage_information_personal_check_in_relationships")  # 考勤信息
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_personal"


class PersonalForm(ModelForm):
    """
    个人信息Form
    """

    def clean(self):
        cleaned_data = super(PersonalForm, self).clean()

        # 检查数据有效性
        # 手机号必须为数字
        if 'phone' in cleaned_data:
            phone = cleaned_data['phone']
            if phone != "" and not phone.isdigit():
                msg = u"请确认手机号全部为数字。"
                self._errors["phone"] = self.error_class([msg])
                del cleaned_data["phone"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('sex', 'birthday', 'phone',)


class PersonalDepartmentForm(ModelForm):
    """
    个人所属部门Form
    """
    def clean(self):
        cleaned_data = super(PersonalDepartmentForm, self).clean()
        # 检查数据有效性
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalDepartmentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('department',)


class PersonalStatusForm(ModelForm):
    """
    个人状态Form
    """
    def clean(self):
        cleaned_data = super(PersonalStatusForm, self).clean()
        # 检查数据有效性
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalStatusForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('status',)


class JobForm(ModelForm):
    """
    工作经历Form
    """

    def clean(self):
        cleaned_data = super(JobForm, self).clean()

        # 检查数据有效性
        # 结束日期不能小于开始日期
        if 'end_date' in cleaned_data:
            start_date = cleaned_data['start_date']
            end_date = cleaned_data['end_date']
            if end_date <= start_date:
                msg = u"结束日期不能小于等于开始日期"
                self._errors["end_date"] = self.error_class([msg])
                del cleaned_data["end_date"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Job
        fields = ('start_date', 'end_date', 'company', 'position',)


class EducationForm(ModelForm):
    """
    教育经历Form
    """

    def clean(self):
        cleaned_data = super(EducationForm, self).clean()

        # 检查数据有效性
        # 结束日期不能小于开始日期
        if 'end_date' in cleaned_data:
            start_date = cleaned_data['start_date']
            end_date = cleaned_data['end_date']
            if end_date <= start_date:
                msg = u"结束日期不能小于等于开始日期"
                self._errors["end_date"] = self.error_class([msg])
                del cleaned_data["end_date"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(EducationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Education
        fields = ('start_date', 'end_date', 'school', 'kind',)


class FamilyForm(ModelForm):
    """
    家庭信息Form
    """

    def clean(self):
        cleaned_data = super(FamilyForm, self).clean()

        # 检查数据有效性
        # 手机号必须为数字
        if 'mobile_phone' in cleaned_data:
            mobile_phone = cleaned_data['mobile_phone']
            if mobile_phone != "" and not mobile_phone.isdigit():
                msg = u"请确认手机号全部为数字。"
                self._errors["mobile_phone"] = self.error_class([msg])
                del cleaned_data["mobile_phone"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(FamilyForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Family
        fields = ('name', 'relationship', 'mobile_phone',)

templates/information/contacts.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extfilters %}
{% block title %} - 通讯录一览{% endblock %}
{% block content %}
    <input type="hidden" id="total_count" value="{{ total_count }}"/>
    <input type="hidden" id="amd_module" value="{% static "js/views/information_personal.js" %}"/>
    <div class="container" style="margin-top:60px;">
        <div class="page_header">
            <ul class="bc">
                <li><a href="/">主页</a> <span class="divider">/</span></li>
                <li class="active">通讯录一览</li>
            </ul>
            <form class="form-search search_box">
                <div class="input-append">
                    <input type="text" class="span2 search-query" id="queryKey" value="{{ query_params.query }}">
                    <button type="button" class="btn default_button" id="btnSearch">搜索</button>
                </div>
            </form>
        </div>
        {% if total_count == 0 %}
            <div class="row">
                <div class="span12 alert alert-block">
                    <h4>注意!</h4>
                    您搜索的结果不存在，请确认后重试。
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="span12" style="text-align: right;padding-top: 20px;">
                    <span class="label">共{{ total_count }}条记录</span>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <div class="search_result_list">
                        <table class="table table-bordered table-hover" >
                            <thead>
                                <tr>
                                    <th>编号</th>
                                    <th>姓名</th>
                                    <th>身份</th>
                                    <th>手机号</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                    <tr>
                                        <td class="cell_center">{{ forloop.counter }}</td>
                                        <td class="cell_center">{{ user.get_full_name }}</td>
                                        <td class="cell_center">{{ user.groups.all|first }}</td>
                                        <td class="cell_center">{{ user.personal.phone|default_if_none:"" }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/information/education_edit.html
{% load extfilters %}
{#{% load humanize %}#}
<div class="modal hide fade" id="education_edit">
    <form class="form-horizontal" action="/information/personal/{{ user_pk }}/education/edit/action/" id="frmEditEducation" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_pk" id="id_user_pk" value="{{ user_pk|default_if_none:"" }}"/>
        <input type="hidden" name="id" id="pk" value="{{ education.instance.id|default_if_none:"" }}"/>
        <input type="hidden" name="education_validation" id="id_education_validation" value="{{ education_validation }}">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>编辑教育经历</h3>
        </div>
        <div class="modal-body">
            {% if education.non_field_errors %}
                {% with education.non_field_errors|first as error %}
                    <div class="control-group">
                        <div class="controls"><span class="error_message">{{ error }}</span></div>
                    </div>
                {% endwith %}
            {% endif %}
            <div class="control-group">
                <label class="control-label" for="id_start_date">开始时间</label>
                <div class="controls">
                    <div class="input-append date education_start_date" data-date="{{ education.start_date.value|default_if_none:""|format_date }}" data-date-format="yyyy-mm-dd">
                        <input type="text" class="span2 {% if education.start_date.errors %} error_flg{% endif %}"
                               id="id_start_date" name="start_date" value="{{ education.start_date.value|default_if_none:""|format_date }}" readonly/>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                    {% if education.start_date.errors %}
                        {% with education.start_date.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_end_date">结束时间</label>
                <div class="controls">
                    <div class="input-append date education_end_date" data-date="{{ education.end_date.value|default_if_none:""|format_date }}" data-date-format="yyyy-mm-dd">
                        <input type="text" class="span2 {% if education.end_date.errors %} error_flg{% endif %}"
                               id="id_end_date" name="end_date" value="{{ education.end_date.value|default_if_none:""|format_date }}" readonly/>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                    {% if education.end_date.errors %}
                        {% with education.end_date.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_school">学校名称</label>
                <div class="controls">
                    <input type="text" class="span2 {% if education.school.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_school" name="school" value="{{ education.school.value|default_if_none:"" }}"/>
                    {% if education.school.errors %}
                        {% with education.school.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_kind">种类</label>
                <div class="controls">
                    <input type="text" class="span2 {% if education.kind.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_kind" name="kind" value="{{ education.kind.value|default_if_none:"" }}"/>
                    {% if education.kind.errors %}
                        {% with education.kind.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal" >关闭</button>
            <button type="button" class="btn btn-primary btn-education-edit">保存</button>
        </div>
    </form>
</div>

templates/information/education_list.html
{% load extfilters %}
{#{% load humanize %}#}
{% if education_count == 0 %}
    <div class="row">
        <div class="span8 alert alert-block" style="margin-left: 120px">
            <h4>注意!</h4>
            还未添加任何教育经历
                <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1), 添加： 逐条添加，每一次只能生成一条教育经历信息；
        </div>
        <div class="span8" style="margin-left: 120px">
            <a class="btn btn-primary btn-small education_edit" href="#" data-form="/information/personal/{{ user_pk }}/education/add/">添加</a>
        </div>
    </div>
{% else %}
    <div class="row">
        <div class="span4" style="margin-left: 120px">
            <div class="btn-toolbar">
                <div class="btn-group">
                    <a class="btn" id="btnNew" data-toggle="dropdown" href="#"><i class="icon-plus"></i></a>
                    <ul class="dropdown-menu">
                        <li><a class="education_edit" href="#" data-form="/information/personal/{{ user_pk }}/education/add/">添加</a></li>
                    </ul>
                    <a class="btn disabled" id="btnDelete"><i class="icon-trash"></i></a>
                </div>
            </div>
        </div>
        <div class="span4" style="text-align: right;padding-top: 20px;">
            <span class="label">共{{ education_count }}条信息</span>
        </div>
    </div>
    <div class="row">
        <div class="span8" style="margin-left: 120px">
            <div class="search_result_list">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th class="check_column" style="vertical-align:middle"><input type="checkbox" id="checkSelectAll"/></th>
                        <th style="vertical-align:middle">开始时间</th>
                        <th style="vertical-align:middle">结束时间</th>
                        <th style="vertical-align:middle">学校名称</th>
                        <th style="vertical-align:middle">种类</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for education in education_list %}
                        <tr>
                            <td class="cell_center"><input type="checkbox" class="list_selector" pk="{{ education.id }}"/></td>
                            <td class="cell_center">{{ education.start_date|format_date }}</td>
                            <td class="cell_center">{{ education.end_date|format_date }}</td>
                            <td class="cell_center">
                                <a class="btn-link education_edit" href="#" data-form="/information/personal/{{ user_pk }}/education/edit/{{ education.id }}/">{{ education.school }}</a>
                            </td>
                            <td class="cell_center">{{ education.kind }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}

templates/information/family_edit.html
{% load extfilters %}
{#{% load humanize %}#}
<div class="modal hide fade" id="family_edit">
    <form class="form-horizontal" action="/information/personal/{{ user_pk }}/family/edit/action/" id="frmEditFamily" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_pk" id="id_user_pk" value="{{ user_pk|default_if_none:"" }}"/>
        <input type="hidden" name="id" id="pk" value="{{ family.instance.id|default_if_none:"" }}"/>
        <input type="hidden" name="family_validation" id="id_family_validation" value="{{ family_validation }}">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>编辑家庭信息</h3>
        </div>
        <div class="modal-body">
            {% if family.non_field_errors %}
                {% with family.non_field_errors|first as error %}
                    <div class="control-group">
                        <div class="controls"><span class="error_message">{{ error }}</span></div>
                    </div>
                {% endwith %}
            {% endif %}
            <div class="control-group">
                <label class="control-label" for="id_name">名称</label>
                <div class="controls">
                    <input type="text" class="span2 {% if family.name.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_name" name="name" value="{{ family.name.value|default_if_none:"" }}"/>
                    {% if family.name.errors %}
                        {% with family.name.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_relationship">关系</label>
                <div class="controls">
                    <input type="text" class="span2 {% if family.relationship.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_relationship" name="relationship" value="{{ family.relationship.value|default_if_none:"" }}"/>
                    {% if family.relationship.errors %}
                        {% with family.relationship.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_mobile_phone">手机号</label>
                <div class="controls">
                    <input type="text" class="span2 {% if family.mobile_phone.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_mobile_phone" name="mobile_phone" value="{{ family.mobile_phone.value|default_if_none:"" }}"/>
                    {% if family.mobile_phone.errors %}
                        {% with family.mobile_phone.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal" >关闭</button>
            <button type="button" class="btn btn-primary btn-family-edit">保存</button>
        </div>
    </form>
</div>

templates/information/job_edit.html
{% load extfilters %}
{#{% load humanize %}#}
<div class="modal hide fade" id="job_edit">
    <form class="form-horizontal" action="/information/personal/{{ user_pk }}/job/edit/action/" id="frmEditJob" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_pk" id="id_user_pk" value="{{ user_pk|default_if_none:"" }}"/>
        <input type="hidden" name="id" id="pk" value="{{ job.instance.id|default_if_none:"" }}"/>
        <input type="hidden" name="job_validation" id="id_job_validation" value="{{ job_validation }}">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3>编辑工作经历</h3>
        </div>
        <div class="modal-body">
            {% if job.non_field_errors %}
                {% with job.non_field_errors|first as error %}
                    <div class="control-group">
                        <div class="controls"><span class="error_message">{{ error }}</span></div>
                    </div>
                {% endwith %}
            {% endif %}
            <div class="control-group">
                <label class="control-label" for="id_start_date">开始时间</label>
                <div class="controls">
                    <div class="input-append date job_start_date" data-date="{{ job.start_date.value|default_if_none:""|format_date }}" data-date-format="yyyy-mm-dd">
                        <input type="text" class="span2 {% if job.start_date.errors %} error_flg{% endif %}"
                               id="id_start_date" name="start_date" value="{{ job.start_date.value|default_if_none:""|format_date }}" readonly/>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                    {% if job.start_date.errors %}
                        {% with job.start_date.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_end_date">结束时间</label>
                <div class="controls">
                    <div class="input-append date job_end_date" data-date="{{ job.end_date.value|default_if_none:""|format_date }}" data-date-format="yyyy-mm-dd">
                        <input type="text" class="span2 {% if job.end_date.errors %} error_flg{% endif %}"
                               id="id_end_date" name="end_date" value="{{ job.end_date.value|default_if_none:""|format_date }}" readonly/>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                    {% if job.end_date.errors %}
                        {% with job.end_date.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_company">公司名称</label>
                <div class="controls">
                    <input type="text" class="span2 {% if job.company.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_company" name="company" value="{{ job.company.value|default_if_none:"" }}"/>
                    {% if job.company.errors %}
                        {% with job.company.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_position">职位</label>
                <div class="controls">
                    <input type="text" class="span2 {% if job.position.errors %} error_flg{% endif %}" maxlength="30"
                           id="id_position" name="position" value="{{ job.position.value|default_if_none:"" }}"/>
                    {% if job.position.errors %}
                        {% with job.position.errors|first as error %}
                            <br/>
                            <span class="error_message">{{ error }}</span>
                        {% endwith %}
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal" >关闭</button>
            <button type="button" class="btn btn-primary btn-job-edit">保存</button>
        </div>
    </form>
</div>