comprehensive/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'cc'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('comprehensive.views',
    # 部门管理
    url(r'^department/list/$', 'department_list_view'),  # 部门一览view
    url(r'^department/add/$', 'department_add_view'),  # 部门增加view
    url(r'^department/add/action/$', 'department_add_action'),  # 部门增加action
    url(r'^department/edit/(\d*)/$', 'department_edit_view'),  # 部门修改view
    url(r'^department/edit/action/$', 'department_edit_action'),  # 部门修改action
    url(r'^department/delete/action/$', 'department_delete_action'),  # 部门删除action

    url(r'^department/set/$', 'department_set_view'),  # 人员部门配置view
    url(r'^department/set/edit/action/$', 'department_set_edit_action'),  # 人员部门配置action

    url(r'^status/set/edit/action/$', 'status_set_edit_action'),  # 人员状态配置action

    # 签到
    url(r'^check_in/(\d*)/$', 'check_in_personal_view'),  # 个人考勤view
    url(r'^check_in/(\d*)/list/$', 'check_in_personal_list_view'),  # 个人考勤list view
    url(r'^check_in/all/list/$', 'check_in_all_list_view'),  # 所有人考勤记录view
    url(r'^check_in/action/$', 'check_in_action'),  # 签到action

    )

notice/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'cc'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('notice.views',
    # 公告信息

    url(r'^add/$', 'notice_add_view'),
    url(r'^add/action/$', 'notice_add_action'),
    url(r'^delete/action/$', 'notice_delete_action'),
    url(r'^edit/(\d*)/$', 'notice_edit_view'),
    url(r'^edit/action/$', 'notice_edit_action'),
    url(r'^list/$', 'notice_list_view'),
    url(r'^(\d*)/$', 'notice_view_view'),

    )

personnel_management_system/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'personnel_management_system.views.home', name='home'),
    # url(r'^personnel_management_system/', include('personnel_management_system.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # 默认主页
    url(r'^$', "personnel_management_system.views.index_view"),

    # 账户管理模块
    url(r'^account/', include('account.urls')),

    # 基础信息模块
    url(r'^information/', include('information.urls')),

    # 综合管理模块
    url(r'^comprehensive/', include('comprehensive.urls')),

    # 公告模块
    url(r'^notice/', include('notice.urls')),
)

comprehensive/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.forms import ModelForm, Form, DateField, CharField
from django import forms
from django.utils.translation import ugettext_lazy as _


class Department(models.Model):
    """
    部门
    """
    name = models.CharField(u"名称", max_length=255)  # 公司名称
    description = models.CharField(u"部门描述", null=True, blank=True, max_length=255)  # 部门描述
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    def get_name(self):
        """返回部门名称"""
        return self.name

    class Meta:
        db_table = "hr_manage_comprehensive_department"


class DepartmentForm(ModelForm):
    """
    部门信息Form
    """
    mode = forms.IntegerField(required=False)

    def clean(self):
        cleaned_data = super(DepartmentForm, self).clean()

        # 检查数据有效性
        # 添加模式下检查名称是否唯一
        if 'name' in cleaned_data and cleaned_data['mode']:
            name = cleaned_data['name']
            if Department.objects.filter(name=name).exclude(delete_flg=True).count() > 0:
                msg = u"该名称已存在。"
                self._errors["name"] = self.error_class([msg])

                del cleaned_data["name"]
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(DepartmentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Department
        fields = ('name', 'description',)


class CheckIn(models.Model):
    """
    考勤
    """
    personal_id = models.IntegerField(u'人员id', max_length=255)  # 人员id（逻辑外键）
    # personal = models.ForeignKey(Personal, null=True, blank=True, related_name="check_in_belong_to")  # 所属个人信息
    date = models.DateField(auto_now_add=True)  # 创建日期
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期时间
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期

    class Meta:
        db_table = "hr_manage_comprehensive_check_in"


class CheckInForm(ModelForm):
    """
    考勤Form
    """
    mode = forms.IntegerField(required=False)

    def clean(self):
        cleaned_data = super(CheckInForm, self).clean()

        # 检查数据有效性
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(CheckInForm, self).__init__(*args, **kwargs)

    class Meta:
        model = CheckIn
        fields = ('personal_id',)

information/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.forms import ModelForm, Form, DateField, CharField
from django import forms
from django.utils.translation import ugettext_lazy as _

from comprehensive.models import Department, CheckIn
from utility.constant import PERSONAL_SEX_MALE, PERSONAL_STATUS_CHOICE, PERSONAL_STATUS_WORK


class Job(models.Model):
    """
    工作经历
    """
    start_date = models.DateField(u"开始日")  # 工作开始日
    end_date = models.DateField(u"结束日")  # 工作结束日
    company = models.CharField(u"公司名称", max_length=255)  # 公司名称
    position = models.CharField(u"职位", max_length=255)  # 职位
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_job"


class Education(models.Model):
    """
    教育经历
    """
    start_date = models.DateField(u"开始日")  # 开始日
    end_date = models.DateField(u"结束日")  # 结束日
    school = models.CharField(u"学校名称", max_length=255)  # 学校名称
    kind = models.CharField(u"种类", max_length=255)  # 种类
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_education"


class Family(models.Model):
    """
    家庭信息
    """
    name = models.CharField(u"名称", max_length=255)  # 名称
    relationship = models.CharField(u"关系", max_length=255)  # 关系
    mobile_phone = models.CharField(u'手机号', null=True, blank=True, max_length=100)  # 手机号
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_family"


class Personal(models.Model):
    """
    个人信息
    """
    sex = models.PositiveIntegerField(u"性别", default=PERSONAL_SEX_MALE)  # 性别
    birthday = models.DateField(u"出生年月", null=True, blank=True,)  # 出生年月
    phone = models.CharField(u'手机号', null=True, blank=True, max_length=100)  # 手机号
    status = models.PositiveSmallIntegerField(u"员工状态", blank=True, choices=PERSONAL_STATUS_CHOICE, default=PERSONAL_STATUS_WORK)  # 员工状态
    department = models.ForeignKey(Department, null=True, blank=True, related_name="belong_to_personal")  # 个人所属部门
    job = models.ManyToManyField(Job, null=True, blank=True, related_name="personal_job",
                                 db_table="hr_manage_information_personal_job_relationships")  # 工作经历
    education = models.ManyToManyField(Education, null=True, blank=True, related_name="personal_education",
                                       db_table="hr_manage_information_personal_education_relationships")  # 教育经历
    family = models.ManyToManyField(Family, null=True, blank=True, related_name="personal_family",
                                    db_table="hr_manage_information_personal_family_relationships")  # 家庭信息
    check_in = models.ManyToManyField(CheckIn, null=True, blank=True, related_name="personal_check_in",
                                      db_table="hr_manage_information_personal_check_in_relationships")  # 考勤信息
    create_datetime = models.DateTimeField(auto_now_add=True)  # 创建日期
    update_datetime = models.DateTimeField(auto_now=True)  # 更新日期
    delete_flg = models.BooleanField(default=False)  # 删除标志位

    class Meta:
        db_table = "hr_manage_information_personal"


class PersonalForm(ModelForm):
    """
    个人信息Form
    """

    def clean(self):
        cleaned_data = super(PersonalForm, self).clean()

        # 检查数据有效性
        # 手机号必须为数字
        if 'phone' in cleaned_data:
            phone = cleaned_data['phone']
            if phone != "" and not phone.isdigit():
                msg = u"请确认手机号全部为数字。"
                self._errors["phone"] = self.error_class([msg])
                del cleaned_data["phone"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('sex', 'birthday', 'phone',)


class PersonalDepartmentForm(ModelForm):
    """
    个人所属部门Form
    """
    def clean(self):
        cleaned_data = super(PersonalDepartmentForm, self).clean()
        # 检查数据有效性
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalDepartmentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('department',)


class PersonalStatusForm(ModelForm):
    """
    个人状态Form
    """
    def clean(self):
        cleaned_data = super(PersonalStatusForm, self).clean()
        # 检查数据有效性
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PersonalStatusForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Personal
        fields = ('status',)


class JobForm(ModelForm):
    """
    工作经历Form
    """

    def clean(self):
        cleaned_data = super(JobForm, self).clean()

        # 检查数据有效性
        # 结束日期不能小于开始日期
        if 'end_date' in cleaned_data:
            start_date = cleaned_data['start_date']
            end_date = cleaned_data['end_date']
            if end_date <= start_date:
                msg = u"结束日期不能小于等于开始日期"
                self._errors["end_date"] = self.error_class([msg])
                del cleaned_data["end_date"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Job
        fields = ('start_date', 'end_date', 'company', 'position',)


class EducationForm(ModelForm):
    """
    教育经历Form
    """

    def clean(self):
        cleaned_data = super(EducationForm, self).clean()

        # 检查数据有效性
        # 结束日期不能小于开始日期
        if 'end_date' in cleaned_data:
            start_date = cleaned_data['start_date']
            end_date = cleaned_data['end_date']
            if end_date <= start_date:
                msg = u"结束日期不能小于等于开始日期"
                self._errors["end_date"] = self.error_class([msg])
                del cleaned_data["end_date"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(EducationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Education
        fields = ('start_date', 'end_date', 'school', 'kind',)


class FamilyForm(ModelForm):
    """
    家庭信息Form
    """

    def clean(self):
        cleaned_data = super(FamilyForm, self).clean()

        # 检查数据有效性
        # 手机号必须为数字
        if 'mobile_phone' in cleaned_data:
            mobile_phone = cleaned_data['mobile_phone']
            if mobile_phone != "" and not mobile_phone.isdigit():
                msg = u"请确认手机号全部为数字。"
                self._errors["mobile_phone"] = self.error_class([msg])
                del cleaned_data["mobile_phone"]

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(FamilyForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Family
        fields = ('name', 'relationship', 'mobile_phone',)

templates/comprehensive/check_in_all_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extfilters %}
{% block title %} - 查看考勤{% endblock %}
{% block content %}
    <input type="hidden" id="total_count" value="{{ total_count }}"/>
    <input type="hidden" id="amd_module" value="{% static "js/views/check_in_all.js" %}"/>
    <input type="hidden" name="user_id" id="user_id" value="{{ user.id }}"/>
{% for key,value in query_params.items %}
    <input type="hidden" id="qs_{{ key }}" value="{{ value }}"/>
{% endfor %}
    <div class="container" style="margin-top:60px;">
        <div class="page_header">
            <ul class="bc">
                <li><a href="/">主页</a> <span class="divider">/</span></li>
                <li class="active">考勤一览</li>
            </ul>
            <form class="form-search search_box">
                <div class="input-append">
                    <input type="text" class="span2 search-query" id="queryKey" value="{{ query_params.query }}">
                    <button type="button" class="btn default_button" id="btnSearch">搜索</button>
                </div>
            </form>
        </div>

        <div id="CheckInList">
        {% if total_count == 0 %}
            <div class="row">
                <div class="span12 alert alert-block">
                    <h4>注意!</h4>
                    还没有考勤记录，请先签到。
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="span12" style="text-align: right;padding-top: 20px;">
                    <span class="label">共{{ total_count }}条记录</span>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <div class="search_result_list">
                        <table class="table table-bordered table-hover" >
                            <thead>
                                <tr>
                                    <th>姓名</th>
                                    <th>身份</th>
                                    <th><a href="#" class="data_column" sort_key="da">日期</a></th>
                                    <th>首次</th>
                                    <th>末次</th>
                                    <th>时长</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in check_in%}
                                    <tr>
                                        <td class="cell_center">{{ item.personal_id|get_name }}</td>
                                        <td class="cell_center">{{ item.personal_id|get_group }}</td>
                                        <td class="cell_center">{{ item.date|format_date }}</td>
                                        <td class="cell_center">{{ item.create_datetime|format_datetime }}</td>
                                        <td class="cell_center">{{ item.update_datetime|format_datetime }}</td>
                                        <td class="cell_center">{{ item.update_datetime|sub_datetime:item.create_datetime }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                        </table>
                        {% if need_pagination %}
                            <div class="pagination pagination-centered pagination-small" style="margin-top:-10px;">
                                <ul>
                                    <li id="btnPrevPage"><a href="#">前页</a></li>
                                    <li id="btnNextPage"><a href="#">次页</a></li>
                                </ul>
                                <div class="pull-right label" id="lblPageCounter">
                                    0/0页
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/comprehensive/check_in_personal_list.html
{% load extfilters %}
{#{% load humanize %}#}
{% if total_count == 0 %}
    <div class="row">
        <div class="span12 alert alert-block">
            <h4>注意!</h4>
            您还没有考勤记录，请先签到。
        </div>

        <div class="span1">
            <input type="hidden" name="personal_id" id="personal_id" value="{{ user.personal.id }}"/>
            <button class="btn btn-success" data-url="/comprehensive/check_in/action/" type="button">签到</button>
        </div>
    </div>
{% else %}
    <div class="row">
        <div class="span1">
            <input type="hidden" name="personal_id" id="personal_id" value="{{ user.personal.id }}"/>
            <button class="btn btn-success" data-url="/comprehensive/check_in/action/" type="button">签到</button>
        </div>
    </div>

    <div class="row">
        <div class="span12" style="text-align: right;padding-top: 20px;">
            <span class="label">共{{ total_count }}条记录</span>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <div class="search_result_list">
                <table class="table table-bordered table-hover" >
                    <thead>
                        <tr>
                            <th>姓名</th>
                            <th>日期</th>
                            <th>首次</th>
                            <th>末次</th>
                            <th>时长</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in check_in %}
                            <tr>
                                <td class="cell_center">{{ user.full_name }}</td>
                                <td class="cell_center">{{ item.date|format_date }}</td>
                                <td class="cell_center">{{ item.create_datetime|format_datetime }}</td>
                                <td class="cell_center">{{ item.update_datetime|format_datetime }}</td>
                                <td class="cell_center">{{ item.update_datetime|sub_datetime:item.create_datetime }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                </table>
                {% if need_pagination %}
                    <div class="pagination pagination-centered pagination-small" style="margin-top:-10px;">
                        <ul>
                            <li id="btnPrevPage"><a href="#">前页</a></li>
                            <li id="btnNextPage"><a href="#">次页</a></li>
                        </ul>
                        <div class="pull-right label" id="lblPageCounter">
                            0/0页
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}

templates/comprehensive/check_in_personal_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% load extfilters %}
{% block title %} - 查看考勤{% endblock %}
{% block content %}
    <input type="hidden" id="total_count" value="{{ total_count }}"/>
    <input type="hidden" id="amd_module" value="{% static "js/views/check_in.js" %}"/>
    <input type="hidden" name="user_id" id="user_id" value="{{ user.id }}"/>
    <div class="container" style="margin-top:60px;">
        <div class="page_header">
            <ul class="bc">
                <li><a href="/">主页</a> <span class="divider">/</span></li>
                <li><a href="/comprehensive/check_in/list/">考勤一览</a> <span class="divider">/</span></li>
                <li class="active">{{ user.full_name }}</li>
            </ul>
        </div>
        {% if total_count == 0 %}
            <div class="row">
                <div class="span12 alert alert-block">
                    <h4>注意!</h4>
                    您还没有考勤记录，请先签到。
                </div>

                <div class="span1">
                    <input type="hidden" name="personal_id" id="personal_id" value="{{ user.personal.id }}"/>
                    <button class="btn btn-success" data-url="/comprehensive/check_in/action/" type="button">签到</button>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="span1">
                    <input type="hidden" name="personal_id" id="personal_id" value="{{ user.personal.id }}"/>
                    <button class="btn btn-success" data-url="/comprehensive/check_in/action/" type="button">签到</button>
                </div>
            </div>

            <div class="row">
                <div class="span12" style="text-align: right;padding-top: 20px;">
                    <span class="label">共{{ total_count }}条记录</span>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <div class="search_result_list">
                        <table class="table table-bordered table-hover" >
                            <thead>
                                <tr>
                                    <th>姓名</th>
                                    <th>日期</th>
                                    <th>首次</th>
                                    <th>末次</th>
                                    <th>时长</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in check_in %}
                                    <tr>
                                        <td class="cell_center">{{ user.full_name }}</td>
                                        <td class="cell_center">{{ item.date|format_date }}</td>
                                        <td class="cell_center">{{ item.create_datetime|format_datetime }}</td>
                                        <td class="cell_center">{{ item.update_datetime|format_datetime }}</td>
{#                                        <td class="cell_center">{{ item.create_datetime-item.update_datetime }}</td>#}
                                    </tr>
                                {% endfor %}
                                </tbody>
                        </table>
                        {% if need_pagination %}
                            <div class="pagination pagination-centered pagination-small" style="margin-top:-10px;">
                                <ul>
                                    <li id="btnPrevPage"><a href="#">前页</a></li>
                                    <li id="btnNextPage"><a href="#">次页</a></li>
                                </ul>
                                <div class="pull-right label" id="lblPageCounter">
                                    0/0页
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/comprehensive/department_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}添加部门{% endblock %}
{% block content %}
    <input type="hidden" id="amd_module" value="{% static "js/views/department_add.js" %}"/>
    <div class="container" style="margin-top:60px;">
        <div class="page_header">
            <ul class="bc">
                <li><a href="/">主页</a> <span class="divider">/</span></li>
                <li><a href="/comprehensive/department/list/">部门一览</a> <span class="divider">/</span></li>
                <li class="active">添加部门</li>
            </ul>
        </div>
        <form class="form-horizontal" action="/comprehensive/department/add/action/" id="frmAddDepartment" method="post">
            {% csrf_token %}
            <input type="hidden" name="redirect_url" id="redirect_url" value="{{ redirect_url|default_if_none:"" }}"/>
            <input type="hidden" name="mode" value="1"/>
            <div class="well well-large fly_left_well">
                <div class="control-group">
                    <label class="control-label" for="txtName">名称</label>
                    <div class="controls">
                        <input type="text" id="txtName" name="name" class="highlight first_focus{% if form.name.errors %} error_flg{% endif %}" maxlength="30" value="{{ form.name.value|default_if_none:"" }}"/>
                        {% if form.name.errors %}
                            {% with form.name.errors|first as error %}
                                <br/><span class="error_message">{{ error }}</span>
                            {% endwith %}
                        {% endif %}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="txtDescription">描述</label>
                    <div class="controls">
                        <input type="text" id="txtDescription" name="description" class="highlight input{% if form.description.errors %} error_flg{% endif %}" maxlength="30" value="{{ form.description.value|default_if_none:"" }}"/>
                        {% if form.description.errors %}
                            {% with form.description.errors|first as error %}
                                <br/><span class="error_message">{{ error }}</span>
                            {% endwith %}
                        {% endif %}
                    </div>
                </div>

                <div class="control-group">
                    <div class="controls">
                        <button type="button" id="btnSave" class="btn btn-primary default_button">保存</button>
                        <button type="button" id="btnReturn" class="btn">返回</button>
                    </div>
                </div>
                {% if form.non_field_errors %}
                    {% with form.non_field_errors|first as error %}
                        <div class="control-group">
                            <div class="controls"><span class="error_message">{{ error }}</span></div>
                        </div>
                    {% endwith %}
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

templates/comprehensive/department_set.html
{% extends "base.html" %}
{% load extfilters %}
{% load staticfiles %}
{#{% load humanize %}#}
{% block title %} - 部门管理{% endblock %}
{% block include_css %}
    <link href="{{ STATIC_URL }}css/bootstrap-editable.css" rel="stylesheet"/>
{% endblock %}
{% block content %}
    <input type="hidden" id="amd_module" value="{% static "js/views/department_set.js" %}"/>
    <div class="container" style="margin-top:60px;">
        <div class="page_header">
            <ul class="bc">
                <li><a href="/">主页</a> <span class="divider">/</span></li>
                <li><a href="/comprehensive/department/list/">部门一览</a> <span class="divider">/</span></li>
                <li class="active">部门管理</li>
            </ul>
            <form class="form-search search_box">
                <div class="input-append">
                    <input type="text" class="span2 search-query" id="queryKey" value="{{ query_params.query }}">
                    <button type="button" class="btn default_button" id="btnSearch">搜索</button>
                </div>
            </form>
        </div>
        {% if total_count == 0 %}
            <div class="row">
                <div class="span12 alert alert-block">
                    <h4>注意!</h4>
                    您搜索的结果不存在，请确认后重试。
                </div>
            </div>
        {% else %}
        <div class="span12" style="text-align: right;padding-top: 20px;">
            <span class="label">共{{ total_count }}条记录</span>
        </div>
        <div class="row">
            <div class="span12">
                <div class="search_result_list">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="vertical-align:middle">名称</th>
                            <th style="vertical-align:middle">身份</th>
                            <th style="vertical-align:middle">所属部门</th>
                            <th style="vertical-align:middle">状态</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for form in form_list %}
                            <tr>
                                <td class="cell_center">
                                    <a href="/information/personal/{{ form.id }}/">{{ form.get_full_name }}</a>
                                </td>
                                <td class="cell_center">{{ form.groups.all|first }}</td>
                                <td class="cell_center" id="{{ form.personal.id }}">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle first_focus" id="id_department_trigger" data-toggle="dropdown" data-target="#" href="#"
                                            data-value="{{ form.personal.department.id|default_if_none:"" }}">
                                            {{ form.personal.department.name|default_if_none:"" }}
                                            <div class="caret"></div>
                                        </a>
                                        <ul class="dropdown-menu">
                                            {% for department in departments %}
                                                <li><a href="javascript: void(0);" class="dropdownItem" for="id_department" value="{{ department.id }}" data-url="/comprehensive/department/set/edit/action/">{{ department.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </td>
                                <td class="cell_center">
                                    <a href="javascript: void(0);" data-type="select" class="status" data-original-title="状态" data-url="/comprehensive/status/set/edit/action/"
                                       data-pk="{{ form.personal.id }}" data-value="{{ form.personal.status|get_personal_status }}">
                                        {{ form.personal.status|get_personal_status }}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}